/* Autogenerated from the list of modules */
#include <unistd.h>

#ifdef __cplusplus
extern "C"{
#endif

int vlc_entry__mod (int (*)(void *, void *, int, ...), void *);
int vlc_entry__karaoke (int (*)(void *, void *, int, ...), void *);
int vlc_entry__image (int (*)(void *, void *, int, ...), void *);
int vlc_entry__prefetch (int (*)(void *, void *, int, ...), void *);
int vlc_entry__diracsys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__xml (int (*)(void *, void *, int, ...), void *);
int vlc_entry__invert (int (*)(void *, void *, int, ...), void *);
int vlc_entry__lua (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_smem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scte18 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_es (int (*)(void *, void *, int, ...), void *);
int vlc_entry__fluidsynth (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mono (int (*)(void *, void *, int, ...), void *);
int vlc_entry__afile (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpegvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__voc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__postproc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spatialaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuvp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_description (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cvdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_rtp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__wave (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_avi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__au (int (*)(void *, void *, int, ...), void *);
int vlc_entry__upnp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i422_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_shout (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gaussianblur (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuy2_i420 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_cycle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rotate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_mosaic_bridge (int (*)(void *, void *, int, ...), void *);
int vlc_entry__edgedetection (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vpx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gnutls (int (*)(void *, void *, int, ...), void *);
int vlc_entry__udp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__swscale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__aiff (int (*)(void *, void *, int, ...), void *);
int vlc_entry__syslog (int (*)(void *, void *, int, ...), void *);
int vlc_entry__egl_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__speex (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gradfun (int (*)(void *, void *, int, ...), void *);
int vlc_entry__folder (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vdr (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawaud (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dvdnav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_display (int (*)(void *, void *, int, ...), void *);
int vlc_entry__textst (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_gather (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vorbis (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ty (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_rgb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mlp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spdif (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4audio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__https (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avformat (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_ogg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_delay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__record (int (*)(void *, void *, int, ...), void *);
int vlc_entry__tospdif (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_hevc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_wav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__android_display (int (*)(void *, void *, int, ...), void *);
int vlc_entry__opensles_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__archive (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_chromecast (int (*)(void *, void *, int, ...), void *);
int vlc_entry__gles2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cache_read (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_asf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_duplicate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_10_p010 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__normvol (int (*)(void *, void *, int, ...), void *);
int vlc_entry__flacsys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_avparser (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_realrtsp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cache_block (int (*)(void *, void *, int, ...), void *);
int vlc_entry__hqdn3d (int (*)(void *, void *, int, ...), void *);
int vlc_entry__webvtt (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adaptive (int (*)(void *, void *, int, ...), void *);
int vlc_entry__compressor (int (*)(void *, void *, int, ...), void *);
int vlc_entry__xa (int (*)(void *, void *, int, ...), void *);
int vlc_entry__croppadd (int (*)(void *, void *, int, ...), void *);
int vlc_entry__asf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__twolame (int (*)(void *, void *, int, ...), void *);
int vlc_entry__anaglyph (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demuxdump (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vobsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__telx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_ts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__hds (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__zvbi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__pva (int (*)(void *, void *, int, ...), void *);
int vlc_entry__live555 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__chain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__android_logger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__antiflicker (int (*)(void *, void *, int, ...), void *);
int vlc_entry__caf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpegaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__equalizer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__aes3 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__file_logger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sdp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ugly_resampler (int (*)(void *, void *, int, ...), void *);
int vlc_entry__aom (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_setid (int (*)(void *, void *, int, ...), void *);
int vlc_entry__android_audiotrack (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nsc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__headphone_channel_mixer (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__yuv_rgb_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__inflate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__flaschen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_concat (int (*)(void *, void *, int, ...), void *);
int vlc_entry__uleaddvaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__satip (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__png (int (*)(void *, void *, int, ...), void *);
int vlc_entry__fingerprinter (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__opus (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mpjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__iomx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__svcdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__simple_channel_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__lpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__tta (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nfs (int (*)(void *, void *, int, ...), void *);
int vlc_entry__trivial_channel_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__timecode (int (*)(void *, void *, int, ...), void *);
int vlc_entry__http (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_a52 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__es (int (*)(void *, void *, int, ...), void *);
int vlc_entry__extract (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ogg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_h264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__amem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vhs (int (*)(void *, void *, int, ...), void *);
int vlc_entry__fps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__playlist (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mpg123 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mediacodec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_transcode (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__marq (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawdv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__canvas (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_livehttp (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__chroma_yuv_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__scale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__freeze (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_record (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rv32 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__shm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsdelay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__oldmovie (int (*)(void *, void *, int, ...), void *);
int vlc_entry__noseek (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adjust (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_file (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scaletempo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__libass (int (*)(void *, void *, int, ...), void *);
int vlc_entry__android_window (int (*)(void *, void *, int, ...), void *);
int vlc_entry__skiptags (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__glconv_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__wav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_nv12 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__avcodec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__taglib (int (*)(void *, void *, int, ...), void *);
int vlc_entry__yuy2_i422 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dvdread (int (*)(void *, void *, int, ...), void *);
int vlc_entry__console_logger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dvbsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__file_keystore (int (*)(void *, void *, int, ...), void *);
int vlc_entry__flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__param_eq (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mpgv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_stats (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__memory_keystore (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsdec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__attachment (int (*)(void *, void *, int, ...), void *);
int vlc_entry__float_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_copy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__integer_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_autodel (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rtp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spatializer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mkv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mp4 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ttml (int (*)(void *, void *, int, ...), void *);
int vlc_entry__remap (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i420_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__adf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_chromecast (int (*)(void *, void *, int, ...), void *);
int vlc_entry__soxr (int (*)(void *, void *, int, ...), void *);
int vlc_entry__blend (int (*)(void *, void *, int, ...), void *);
int vlc_entry__ts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__imem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subtitle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_dirac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__oggspots (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spudec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__h26x (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_udp (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__volume_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__demux_cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__i422_i420 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stereo_widen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_av1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dtv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_bridge (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rtpvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_format (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nsv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dvb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__cc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_dts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__x26410b (int (*)(void *, void *, int, ...), void *);
int vlc_entry__theora (int (*)(void *, void *, int, ...), void *);
int vlc_entry__sepia (int (*)(void *, void *, int, ...), void *);
int vlc_entry__decomp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__x264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__tcp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__a52 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scte27 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vod_rtsp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__freetype (int (*)(void *, void *, int, ...), void *);
int vlc_entry__microdns (int (*)(void *, void *, int, ...), void *);
int vlc_entry__vmem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__chorus_flanger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_mms (int (*)(void *, void *, int, ...), void *);
int vlc_entry__g711 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__jpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_standard (int (*)(void *, void *, int, ...), void *);
int vlc_entry__colorthres (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4video (int (*)(void *, void *, int, ...), void *);
int vlc_entry__substx3g (int (*)(void *, void *, int, ...), void *);
int vlc_entry__subsusf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__dolby_surround_decoder (int (*)(void *, void *, int, ...), void *);
int vlc_entry__filesystem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_http (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mp4 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__araw (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_ps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__grey_yuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__directory_demux (int (*)(void *, void *, int, ...), void *);
int vlc_entry__transform (int (*)(void *, void *, int, ...), void *);
int vlc_entry__deinterlace (int (*)(void *, void *, int, ...), void *);
int vlc_entry__scaletempo_pitch (int (*)(void *, void *, int, ...), void *);
int vlc_entry__rawvid (int (*)(void *, void *, int, ...), void *);
int vlc_entry__nuv (int (*)(void *, void *, int, ...), void *);
#ifdef __cplusplus
}
#endif



const void *vlc_static_modules[] = {
 (void *) vlc_entry__mod,
 (void *) vlc_entry__karaoke,
 (void *) vlc_entry__image,
 (void *) vlc_entry__prefetch,
 (void *) vlc_entry__diracsys,
 (void *) vlc_entry__xml,
 (void *) vlc_entry__invert,
 (void *) vlc_entry__lua,
 (void *) vlc_entry__stream_out_smem,
 (void *) vlc_entry__dummy,
 (void *) vlc_entry__scte18,
 (void *) vlc_entry__mjpeg,
 (void *) vlc_entry__stream_out_es,
 (void *) vlc_entry__fluidsynth,
 (void *) vlc_entry__mono,
 (void *) vlc_entry__afile,
 (void *) vlc_entry__packetizer_mpegvideo,
 (void *) vlc_entry__voc,
 (void *) vlc_entry__postproc,
 (void *) vlc_entry__spatialaudio,
 (void *) vlc_entry__yuvp,
 (void *) vlc_entry__stream_out_description,
 (void *) vlc_entry__cvdsub,
 (void *) vlc_entry__stream_out_rtp,
 (void *) vlc_entry__wave,
 (void *) vlc_entry__mux_avi,
 (void *) vlc_entry__au,
 (void *) vlc_entry__upnp,
 (void *) vlc_entry__i422_yuy2,
 (void *) vlc_entry__access_output_shout,
 (void *) vlc_entry__gaussianblur,
 (void *) vlc_entry__yuy2_i420,
 (void *) vlc_entry__stream_out_cycle,
 (void *) vlc_entry__rotate,
 (void *) vlc_entry__stream_out_mosaic_bridge,
 (void *) vlc_entry__edgedetection,
 (void *) vlc_entry__vpx,
 (void *) vlc_entry__gnutls,
 (void *) vlc_entry__udp,
 (void *) vlc_entry__swscale,
 (void *) vlc_entry__aiff,
 (void *) vlc_entry__syslog,
 (void *) vlc_entry__egl_android,
 (void *) vlc_entry__cdg,
 (void *) vlc_entry__speex,
 (void *) vlc_entry__gradfun,
 (void *) vlc_entry__folder,
 (void *) vlc_entry__vdr,
 (void *) vlc_entry__rawaud,
 (void *) vlc_entry__dvdnav,
 (void *) vlc_entry__stream_out_display,
 (void *) vlc_entry__textst,
 (void *) vlc_entry__demux_stl,
 (void *) vlc_entry__stream_out_gather,
 (void *) vlc_entry__vorbis,
 (void *) vlc_entry__stl,
 (void *) vlc_entry__gain,
 (void *) vlc_entry__ty,
 (void *) vlc_entry__i420_rgb,
 (void *) vlc_entry__packetizer_mlp,
 (void *) vlc_entry__spdif,
 (void *) vlc_entry__packetizer_mpeg4audio,
 (void *) vlc_entry__ftp,
 (void *) vlc_entry__https,
 (void *) vlc_entry__avformat,
 (void *) vlc_entry__mux_ogg,
 (void *) vlc_entry__stream_out_delay,
 (void *) vlc_entry__record,
 (void *) vlc_entry__tospdif,
 (void *) vlc_entry__packetizer_hevc,
 (void *) vlc_entry__mux_wav,
 (void *) vlc_entry__android_display,
 (void *) vlc_entry__opensles_android,
 (void *) vlc_entry__vc1,
 (void *) vlc_entry__avi,
 (void *) vlc_entry__archive,
 (void *) vlc_entry__stream_out_chromecast,
 (void *) vlc_entry__gles2,
 (void *) vlc_entry__cache_read,
 (void *) vlc_entry__mux_asf,
 (void *) vlc_entry__stream_out_duplicate,
 (void *) vlc_entry__i420_10_p010,
 (void *) vlc_entry__normvol,
 (void *) vlc_entry__flacsys,
 (void *) vlc_entry__packetizer_avparser,
 (void *) vlc_entry__access_realrtsp,
 (void *) vlc_entry__avio,
 (void *) vlc_entry__cache_block,
 (void *) vlc_entry__hqdn3d,
 (void *) vlc_entry__webvtt,
 (void *) vlc_entry__adaptive,
 (void *) vlc_entry__compressor,
 (void *) vlc_entry__xa,
 (void *) vlc_entry__croppadd,
 (void *) vlc_entry__asf,
 (void *) vlc_entry__twolame,
 (void *) vlc_entry__anaglyph,
 (void *) vlc_entry__demuxdump,
 (void *) vlc_entry__vobsub,
 (void *) vlc_entry__telx,
 (void *) vlc_entry__mux_ts,
 (void *) vlc_entry__hds,
 (void *) vlc_entry__sftp,
 (void *) vlc_entry__zvbi,
 (void *) vlc_entry__pva,
 (void *) vlc_entry__live555,
 (void *) vlc_entry__chain,
 (void *) vlc_entry__android_logger,
 (void *) vlc_entry__antiflicker,
 (void *) vlc_entry__caf,
 (void *) vlc_entry__packetizer_mpegaudio,
 (void *) vlc_entry__equalizer,
 (void *) vlc_entry__aes3,
 (void *) vlc_entry__file_logger,
 (void *) vlc_entry__sdp,
 (void *) vlc_entry__adpcm,
 (void *) vlc_entry__ugly_resampler,
 (void *) vlc_entry__aom,
 (void *) vlc_entry__ps,
 (void *) vlc_entry__stream_out_setid,
 (void *) vlc_entry__android_audiotrack,
 (void *) vlc_entry__nsc,
 (void *) vlc_entry__headphone_channel_mixer,
#ifndef ANDROID_ARMV8A
 (void *) vlc_entry__yuv_rgb_neon,
#endif
 (void *) vlc_entry__inflate,
 (void *) vlc_entry__flaschen,
 (void *) vlc_entry__access_concat,
 (void *) vlc_entry__uleaddvaudio,
 (void *) vlc_entry__satip,
 (void *) vlc_entry__mux_dummy,
 (void *) vlc_entry__png,
 (void *) vlc_entry__fingerprinter,
 (void *) vlc_entry__rawvideo,
 (void *) vlc_entry__opus,
 (void *) vlc_entry__mux_mpjpeg,
 (void *) vlc_entry__iomx,
 (void *) vlc_entry__svcdsub,
 (void *) vlc_entry__simple_channel_mixer,
 (void *) vlc_entry__lpcm,
 (void *) vlc_entry__tta,
 (void *) vlc_entry__nfs,
 (void *) vlc_entry__trivial_channel_mixer,
 (void *) vlc_entry__timecode,
 (void *) vlc_entry__http,
 (void *) vlc_entry__packetizer_a52,
 (void *) vlc_entry__es,
 (void *) vlc_entry__extract,
 (void *) vlc_entry__ogg,
 (void *) vlc_entry__packetizer_h264,
 (void *) vlc_entry__amem,
 (void *) vlc_entry__vhs,
 (void *) vlc_entry__fps,
 (void *) vlc_entry__playlist,
 (void *) vlc_entry__mpg123,
 (void *) vlc_entry__mediacodec,
 (void *) vlc_entry__stream_out_transcode,
 (void *) vlc_entry__access_output_dummy,
 (void *) vlc_entry__marq,
 (void *) vlc_entry__rawdv,
 (void *) vlc_entry__canvas,
 (void *) vlc_entry__access_output_livehttp,
#ifndef ANDROID_ARMV8A
 (void *) vlc_entry__chroma_yuv_neon,
#endif
 (void *) vlc_entry__scale,
 (void *) vlc_entry__freeze,
 (void *) vlc_entry__stream_out_record,
 (void *) vlc_entry__rv32,
 (void *) vlc_entry__shm,
 (void *) vlc_entry__subsdelay,
 (void *) vlc_entry__oldmovie,
 (void *) vlc_entry__noseek,
 (void *) vlc_entry__adjust,
 (void *) vlc_entry__access_output_file,
 (void *) vlc_entry__scaletempo,
 (void *) vlc_entry__libass,
 (void *) vlc_entry__android_window,
 (void *) vlc_entry__skiptags,
 (void *) vlc_entry__stream_out_dummy,
 (void *) vlc_entry__glconv_android,
 (void *) vlc_entry__wav,
 (void *) vlc_entry__i420_nv12,
 (void *) vlc_entry__avcodec,
 (void *) vlc_entry__taglib,
 (void *) vlc_entry__yuy2_i422,
 (void *) vlc_entry__dvdread,
 (void *) vlc_entry__console_logger,
 (void *) vlc_entry__dvbsub,
 (void *) vlc_entry__file_keystore,
 (void *) vlc_entry__flac,
 (void *) vlc_entry__param_eq,
 (void *) vlc_entry__packetizer_flac,
 (void *) vlc_entry__mpgv,
 (void *) vlc_entry__stream_out_stats,
 (void *) vlc_entry__logo,
 (void *) vlc_entry__memory_keystore,
 (void *) vlc_entry__subsdec,
 (void *) vlc_entry__attachment,
 (void *) vlc_entry__float_mixer,
 (void *) vlc_entry__packetizer_copy,
 (void *) vlc_entry__integer_mixer,
 (void *) vlc_entry__stream_out_autodel,
 (void *) vlc_entry__rtp,
 (void *) vlc_entry__spatializer,
 (void *) vlc_entry__mkv,
 (void *) vlc_entry__mux_mp4,
 (void *) vlc_entry__ttml,
 (void *) vlc_entry__remap,
 (void *) vlc_entry__i420_yuy2,
 (void *) vlc_entry__adf,
 (void *) vlc_entry__demux_chromecast,
 (void *) vlc_entry__soxr,
 (void *) vlc_entry__blend,
 (void *) vlc_entry__ts,
 (void *) vlc_entry__imem,
 (void *) vlc_entry__subtitle,
 (void *) vlc_entry__packetizer_dirac,
 (void *) vlc_entry__oggspots,
 (void *) vlc_entry__spudec,
 (void *) vlc_entry__h26x,
 (void *) vlc_entry__access_output_udp,
#ifndef ANDROID_ARMV8A
 (void *) vlc_entry__volume_neon,
#endif
 (void *) vlc_entry__demux_cdg,
 (void *) vlc_entry__i422_i420,
 (void *) vlc_entry__stereo_widen,
 (void *) vlc_entry__packetizer_av1,
 (void *) vlc_entry__dtv,
 (void *) vlc_entry__stream_out_bridge,
 (void *) vlc_entry__rtpvideo,
 (void *) vlc_entry__audio_format,
 (void *) vlc_entry__nsv,
 (void *) vlc_entry__dvb,
 (void *) vlc_entry__cc,
 (void *) vlc_entry__packetizer_dts,
 (void *) vlc_entry__x26410b,
 (void *) vlc_entry__theora,
 (void *) vlc_entry__sepia,
 (void *) vlc_entry__decomp,
 (void *) vlc_entry__x264,
 (void *) vlc_entry__tcp,
 (void *) vlc_entry__a52,
 (void *) vlc_entry__scte27,
 (void *) vlc_entry__vod_rtsp,
 (void *) vlc_entry__freetype,
 (void *) vlc_entry__microdns,
 (void *) vlc_entry__vmem,
 (void *) vlc_entry__packetizer_vc1,
 (void *) vlc_entry__chorus_flanger,
 (void *) vlc_entry__access_mms,
 (void *) vlc_entry__g711,
 (void *) vlc_entry__jpeg,
 (void *) vlc_entry__stream_out_standard,
 (void *) vlc_entry__colorthres,
 (void *) vlc_entry__packetizer_mpeg4video,
 (void *) vlc_entry__substx3g,
 (void *) vlc_entry__subsusf,
 (void *) vlc_entry__dolby_surround_decoder,
 (void *) vlc_entry__filesystem,
 (void *) vlc_entry__access_output_http,
 (void *) vlc_entry__mp4,
 (void *) vlc_entry__araw,
 (void *) vlc_entry__mux_ps,
 (void *) vlc_entry__grey_yuv,
 (void *) vlc_entry__directory_demux,
 (void *) vlc_entry__transform,
 (void *) vlc_entry__deinterlace,
 (void *) vlc_entry__scaletempo_pitch,
 (void *) vlc_entry__rawvid,
 (void *) vlc_entry__nuv,
 (void *)NULL
};
