/* Autogenerated from the list of modules */
#include <unistd.h>

#ifdef __cplusplus
extern "C"{
#endif


int vlc_entry__codec_zvbi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_yuy2_i422 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_yuy2_i420 (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__arm_neon_yuv_rgb_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__video_chroma_yuvp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_yuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_xml_xml (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_xa (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_x264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_x26410b (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_wextern (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_webvtt_webvtt (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_wdummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_wav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_wave (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_splitter_wall (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_vpx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_vorbis (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__arm_neon_volume_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__misc_rtsp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_voc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_vobsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_vmem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__visualization_visual_visual (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_splitter (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_vhs (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_vgl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_vdummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_vdr (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__services_discovery_upnp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_uleaddvaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_resampler_ugly (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_udp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_ty (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_twolame (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_ttml_ttml (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_tta (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mpeg_ts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_trivial (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_transform (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_converter_tospdif (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_timecode (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_theora (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_textst (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_telx (int (*)(void *, void *, int, ...), void *);
int vlc_entry__text_renderer_tdummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_tcp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__meta_engine_tag (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_t140 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logger_syslog (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_swscale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_svcdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_subtitle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_subsusf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_substx3g (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_subsdelay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_subsdec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_transcode_stream_out_transcode (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_stats (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_stream_out_standard (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_smem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_setid (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_stream_out_rtp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_record (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_mosaic_bridge (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_gather (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_es (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_duplicate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_display (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_description (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_delay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_cycle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_chromecast_stream_out_chromecast (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_bridge (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_autodel (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_stereo_widen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_stats (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_spudec_spudec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_resampler_speex_resampler (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_speex (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_spdif (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_spatializer_spatializer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_spatialaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_resampler_soxr (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_smf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_smb2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_skiptags (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_simple_channel_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_shm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_sharpen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_sftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_sepia (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_sdp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_scte27 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_scte18 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_scene (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_scaletempo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_scaletempo_pitch (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_scale (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_satip (int (*)(void *, void *, int, ...), void *);
int vlc_entry__services_discovery_sap (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_rv32 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_rtpvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_rtp_rtp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_rss (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_rotate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_rist (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_ripple (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_remap (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_record (int (*)(void *, void *, int, ...), void *);
int vlc_entry__control_rc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_rawvid (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_rawvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_rawdv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_rawaud (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_pva (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_puzzle (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_psychedelic (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mpeg_ps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_prefetch (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_postproc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_posterize (int (*)(void *, void *, int, ...), void *);
int vlc_entry__services_discovery_podcast (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_png (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_playlist_playlist (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_param_eq (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_vc1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpegvideo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpegaudio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4video (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mpeg4audio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mlp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_mjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_hevc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_h264 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_dts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_copy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_packetizer_avparser (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_av1 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__packetizer_a52 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_opus (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_output_opensles_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_oldmovie (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_oggspots (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_ogg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_nuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_nsv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_nsc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_filter_noseek (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_normvol (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_nfs (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_wav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mpeg_mux_ts (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mpeg_ps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mux_ogg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mpjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_mp4_mp4 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_avi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__mux_asf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mpeg_mpgv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_mpg123 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mp4_mp4 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_motiondetect (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_motionblur (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_mosaic (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_mono (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mod (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mkv_mkv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mjpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_mirror (int (*)(void *, void *, int, ...), void *);
int vlc_entry__services_discovery_microdns (int (*)(void *, void *, int, ...), void *);
int vlc_entry__keystore_memory (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_omxil_mediacodec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_marq (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_magnify (int (*)(void *, void *, int, ...), void *);
int vlc_entry__lua_lua (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_lpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_logo (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_live555 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_ass (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_karaoke (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_jpeg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_invert (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_mixer_integer_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_inflate (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_imem_access (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_image (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_idummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_i422_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_i422_i420 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_i420_yuy2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_i420_rgb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_i420_nv12 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_http_access (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_http (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_hqdn3d (int (*)(void *, void *, int, ...), void *);
int vlc_entry__control_hotkeys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_headphone (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_hds_hds (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mpeg_h26x (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_grey_yuv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_grain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_gradient (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_gradfun (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_gnutls (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_opengl_gles2 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_opengl_glconv_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__control_gestures (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_gaussianblur (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_gain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_g711 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_ftp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_freeze (int (*)(void *, void *, int, ...), void *);
int vlc_entry__text_renderer_freetype_freetype (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_fps (int (*)(void *, void *, int, ...), void *);
int vlc_entry__meta_engine_folder (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_mixer_float_mixer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_flaschen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_flacsys (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_flac (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_fingerprinter (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_filesystem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logger_file (int (*)(void *, void *, int, ...), void *);
int vlc_entry__keystore_file (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_fb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_extract (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_playlist_export (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_mpeg_es (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_erase (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_equalizer (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_opengl_egl_android (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_edummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_edgedetection (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_dynamicoverlay_dynamicoverlay (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_dvdread (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_dvdnav (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_dvbsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_dvb_dvb (int (*)(void *, void *, int, ...), void *);
int vlc_entry__control_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_dtv_dtv (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_dsm_dsm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_channel_mixer_dolby (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_directory (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_demux_stl (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_demuxdump (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_out_chromecast_demux_chromecast (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_demux_cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_deinterlace_deinterlace (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_decomp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_ddummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_dav1d (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_cvdsub (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_croppadd (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logger_console (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_compressor (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_colorthres (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_splitter_clone (int (*)(void *, void *, int, ...), void *);
#ifndef ANDROID_ARMV8A
int vlc_entry__arm_neon_chroma_yuv_neon (int (*)(void *, void *, int, ...), void *);
#endif
int vlc_entry__audio_filter_chorus_flanger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_chroma_chain (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_cdg (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_cc (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_canvas (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_caf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_cache_read (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_cache_block (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_bluescreen (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_blend (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_blendbench (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_ball (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_avi_avi (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_avio (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_avformat_avformat (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_avcodec_avcodec (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_au (int (*)(void *, void *, int, ...), void *);
int vlc_entry__misc_audioscrobbler (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_converter_audio_format (int (*)(void *, void *, int, ...), void *);
int vlc_entry__spu_audiobargraph_v (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_filter_audiobargraph_a (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_asf_asf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_extractor_archive (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_araw (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_aom (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_antiflicker (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_android_android_window (int (*)(void *, void *, int, ...), void *);
int vlc_entry__logger_android_logger (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_output_android_android_display (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_output_android_audiotrack (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_anaglyph (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_output_amem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_alphamask (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_aiff (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_output_afile (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_aes3 (int (*)(void *, void *, int, ...), void *);
int vlc_entry__audio_output_adummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_adpcm (int (*)(void *, void *, int, ...), void *);
int vlc_entry__video_filter_adjust (int (*)(void *, void *, int, ...), void *);
int vlc_entry__stream_filter_adf (int (*)(void *, void *, int, ...), void *);
int vlc_entry__demux_adaptive_adaptive (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_udp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_access_output_shout (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_access_output_rist (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_access_output_livehttp (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_http (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_file (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_output_dummy (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_mms_access_mms (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_imem (int (*)(void *, void *, int, ...), void *);
int vlc_entry__access_concat (int (*)(void *, void *, int, ...), void *);
int vlc_entry__codec_a52 (int (*)(void *, void *, int, ...), void *);
#ifdef __cplusplus
}
#endif



const void *vlc_static_modules[] = {
 (void *)   vlc_entry__codec_zvbi,
 (void *)   vlc_entry__video_chroma_yuy2_i422,
 (void *)   vlc_entry__video_chroma_yuy2_i420,
#ifndef ANDROID_ARMV8A
 (void *)   vlc_entry__arm_neon_yuv_rgb_neon,
#endif
 (void *)   vlc_entry__video_chroma_yuvp,
 (void *)   vlc_entry__video_output_yuv,
 (void *)   vlc_entry__misc_xml_xml,
 (void *)   vlc_entry__demux_xa,
 (void *)   vlc_entry__codec_x264,
 (void *)   vlc_entry__codec_x26410b,
 (void *)   vlc_entry__video_output_wextern,
 (void *)   vlc_entry__codec_webvtt_webvtt,
 (void *)   vlc_entry__video_output_wdummy,
 (void *)   vlc_entry__demux_wav,
 (void *)   vlc_entry__video_filter_wave,
 (void *)   vlc_entry__video_splitter_wall,
 (void *)   vlc_entry__codec_vpx,
 (void *)   vlc_entry__codec_vorbis,
#ifndef ANDROID_ARMV8A
 (void *)   vlc_entry__arm_neon_volume_neon,
#endif
 (void *)   vlc_entry__misc_rtsp,
 (void *)   vlc_entry__demux_voc,
 (void *)   vlc_entry__demux_vobsub,
 (void *)   vlc_entry__video_output_vmem,
 (void *)   vlc_entry__visualization_visual_visual,
 (void *)   vlc_entry__video_output_splitter,
 (void *)   vlc_entry__video_filter_vhs,
 (void *)   vlc_entry__video_output_vgl,
 (void *)   vlc_entry__video_output_vdummy,
 (void *)   vlc_entry__access_vdr,
 (void *)   vlc_entry__demux_vc1,
 (void *)   vlc_entry__services_discovery_upnp,
 (void *)   vlc_entry__codec_uleaddvaudio,
 (void *)   vlc_entry__audio_filter_resampler_ugly,
 (void *)   vlc_entry__access_udp,
 (void *)   vlc_entry__demux_ty,
 (void *)   vlc_entry__codec_twolame,
 (void *)   vlc_entry__codec_ttml_ttml,
 (void *)   vlc_entry__demux_tta,
 (void *)   vlc_entry__demux_mpeg_ts,
 (void *)   vlc_entry__audio_filter_channel_mixer_trivial,
 (void *)   vlc_entry__video_filter_transform,
 (void *)   vlc_entry__audio_filter_converter_tospdif,
 (void *)   vlc_entry__access_timecode,
 (void *)   vlc_entry__codec_theora,
 (void *)   vlc_entry__codec_textst,
 (void *)   vlc_entry__codec_telx,
 (void *)   vlc_entry__text_renderer_tdummy,
 (void *)   vlc_entry__access_tcp,
 (void *)   vlc_entry__meta_engine_tag,
 (void *)   vlc_entry__codec_t140,
 (void *)   vlc_entry__logger_syslog,
 (void *)   vlc_entry__video_chroma_swscale,
 (void *)   vlc_entry__codec_svcdsub,
 (void *)   vlc_entry__demux_subtitle,
 (void *)   vlc_entry__codec_subsusf,
 (void *)   vlc_entry__codec_substx3g,
 (void *)   vlc_entry__spu_subsdelay,
 (void *)   vlc_entry__codec_subsdec,
 (void *)   vlc_entry__stream_out_transcode_stream_out_transcode,
 (void *)   vlc_entry__stream_out_stats,
 (void *)   vlc_entry__stream_out_stream_out_standard,
 (void *)   vlc_entry__stream_out_smem,
 (void *)   vlc_entry__stream_out_setid,
 (void *)   vlc_entry__stream_out_stream_out_rtp,
 (void *)   vlc_entry__stream_out_record,
 (void *)   vlc_entry__stream_out_mosaic_bridge,
 (void *)   vlc_entry__stream_out_gather,
 (void *)   vlc_entry__stream_out_es,
 (void *)   vlc_entry__stream_out_duplicate,
 (void *)   vlc_entry__stream_out_dummy,
 (void *)   vlc_entry__stream_out_display,
 (void *)   vlc_entry__stream_out_description,
 (void *)   vlc_entry__stream_out_delay,
 (void *)   vlc_entry__stream_out_cycle,
 (void *)   vlc_entry__stream_out_chromecast_stream_out_chromecast,
 (void *)   vlc_entry__stream_out_bridge,
 (void *)   vlc_entry__stream_out_autodel,
 (void *)   vlc_entry__codec_stl,
 (void *)   vlc_entry__audio_filter_stereo_widen,
 (void *)   vlc_entry__misc_stats,
 (void *)   vlc_entry__codec_spudec_spudec,
 (void *)   vlc_entry__audio_filter_resampler_speex_resampler,
 (void *)   vlc_entry__codec_speex,
 (void *)   vlc_entry__codec_spdif,
 (void *)   vlc_entry__audio_filter_spatializer_spatializer,
 (void *)   vlc_entry__audio_filter_channel_mixer_spatialaudio,
 (void *)   vlc_entry__audio_filter_resampler_soxr,
 (void *)   vlc_entry__demux_smf,
 (void *)   vlc_entry__access_smb2,
 (void *)   vlc_entry__stream_filter_skiptags,
 (void *)   vlc_entry__audio_filter_channel_mixer_simple_channel_mixer,
 (void *)   vlc_entry__access_shm,
 (void *)   vlc_entry__video_filter_sharpen,
 (void *)   vlc_entry__access_sftp,
 (void *)   vlc_entry__video_filter_sepia,
 (void *)   vlc_entry__access_sdp,
 (void *)   vlc_entry__codec_scte27,
 (void *)   vlc_entry__codec_scte18,
 (void *)   vlc_entry__video_filter_scene,
 (void *)   vlc_entry__audio_filter_scaletempo,
 (void *)   vlc_entry__audio_filter_scaletempo_pitch,
 (void *)   vlc_entry__video_filter_scale,
 (void *)   vlc_entry__access_satip,
 (void *)   vlc_entry__services_discovery_sap,
 (void *)   vlc_entry__video_chroma_rv32,
 (void *)   vlc_entry__codec_rtpvideo,
 (void *)   vlc_entry__access_rtp_rtp,
 (void *)   vlc_entry__spu_rss,
 (void *)   vlc_entry__video_filter_rotate,
 (void *)   vlc_entry__access_rist,
 (void *)   vlc_entry__video_filter_ripple,
 (void *)   vlc_entry__audio_filter_channel_mixer_remap,
 (void *)   vlc_entry__stream_filter_record,
 (void *)   vlc_entry__control_rc,
 (void *)   vlc_entry__demux_rawvid,
 (void *)   vlc_entry__codec_rawvideo,
 (void *)   vlc_entry__demux_rawdv,
 (void *)   vlc_entry__demux_rawaud,
 (void *)   vlc_entry__demux_pva,
 (void *)   vlc_entry__video_filter_puzzle,
 (void *)   vlc_entry__video_filter_psychedelic,
 (void *)   vlc_entry__demux_mpeg_ps,
 (void *)   vlc_entry__stream_filter_prefetch,
 (void *)   vlc_entry__video_filter_postproc,
 (void *)   vlc_entry__video_filter_posterize,
 (void *)   vlc_entry__services_discovery_podcast,
 (void *)   vlc_entry__codec_png,
 (void *)   vlc_entry__demux_playlist_playlist,
 (void *)   vlc_entry__audio_filter_param_eq,
 (void *)   vlc_entry__packetizer_vc1,
 (void *)   vlc_entry__packetizer_mpegvideo,
 (void *)   vlc_entry__packetizer_mpegaudio,
 (void *)   vlc_entry__packetizer_mpeg4video,
 (void *)   vlc_entry__packetizer_mpeg4audio,
 (void *)   vlc_entry__packetizer_mlp,
 (void *)   vlc_entry__packetizer_mjpeg,
 (void *)   vlc_entry__packetizer_hevc,
 (void *)   vlc_entry__packetizer_h264,
 (void *)   vlc_entry__packetizer_flac,
 (void *)   vlc_entry__packetizer_dts,
 (void *)   vlc_entry__packetizer_copy,
 (void *)   vlc_entry__packetizer_packetizer_avparser,
 (void *)   vlc_entry__packetizer_av1,
 (void *)   vlc_entry__packetizer_a52,
 (void *)   vlc_entry__codec_opus,
 (void *)   vlc_entry__audio_output_opensles_android,
 (void *)   vlc_entry__video_filter_oldmovie,
 (void *)   vlc_entry__codec_oggspots,
 (void *)   vlc_entry__demux_ogg,
 (void *)   vlc_entry__demux_nuv,
 (void *)   vlc_entry__demux_nsv,
 (void *)   vlc_entry__demux_nsc,
 (void *)   vlc_entry__demux_filter_noseek,
 (void *)   vlc_entry__audio_filter_normvol,
 (void *)   vlc_entry__access_nfs,
 (void *)   vlc_entry__mux_wav,
 (void *)   vlc_entry__mux_mpeg_mux_ts,
 (void *)   vlc_entry__mux_mpeg_ps,
 (void *)   vlc_entry__mux_mux_ogg,
 (void *)   vlc_entry__mux_mpjpeg,
 (void *)   vlc_entry__mux_mp4_mp4,
 (void *)   vlc_entry__mux_dummy,
 (void *)   vlc_entry__mux_avi,
 (void *)   vlc_entry__mux_asf,
 (void *)   vlc_entry__demux_mpeg_mpgv,
 (void *)   vlc_entry__codec_mpg123,
 (void *)   vlc_entry__demux_mp4_mp4,
 (void *)   vlc_entry__video_filter_motiondetect,
 (void *)   vlc_entry__video_filter_motionblur,
 (void *)   vlc_entry__spu_mosaic,
 (void *)   vlc_entry__audio_filter_channel_mixer_mono,
 (void *)   vlc_entry__demux_mod,
 (void *)   vlc_entry__demux_mkv_mkv,
 (void *)   vlc_entry__demux_mjpeg,
 (void *)   vlc_entry__video_filter_mirror,
 (void *)   vlc_entry__services_discovery_microdns,
 (void *)   vlc_entry__keystore_memory,
 (void *)   vlc_entry__codec_omxil_mediacodec,
 (void *)   vlc_entry__spu_marq,
 (void *)   vlc_entry__video_filter_magnify,
 (void *)   vlc_entry__lua_lua,
 (void *)   vlc_entry__codec_lpcm,
 (void *)   vlc_entry__spu_logo,
 (void *)   vlc_entry__access_live555,
 (void *)   vlc_entry__codec_ass,
 (void *)   vlc_entry__audio_filter_karaoke,
 (void *)   vlc_entry__codec_jpeg,
 (void *)   vlc_entry__video_filter_invert,
 (void *)   vlc_entry__audio_mixer_integer_mixer,
 (void *)   vlc_entry__stream_filter_inflate,
 (void *)   vlc_entry__access_imem_access,
 (void *)   vlc_entry__demux_image,
 (void *)   vlc_entry__access_idummy,
 (void *)   vlc_entry__video_chroma_i422_yuy2,
 (void *)   vlc_entry__video_chroma_i422_i420,
 (void *)   vlc_entry__video_chroma_i420_yuy2,
 (void *)   vlc_entry__video_chroma_i420_rgb,
 (void *)   vlc_entry__video_chroma_i420_nv12,
 (void *)   vlc_entry__access_http_access,
 (void *)   vlc_entry__access_http,
 (void *)   vlc_entry__video_filter_hqdn3d,
 (void *)   vlc_entry__control_hotkeys,
 (void *)   vlc_entry__audio_filter_channel_mixer_headphone,
 (void *)   vlc_entry__stream_filter_hds_hds,
 (void *)   vlc_entry__demux_mpeg_h26x,
 (void *)   vlc_entry__video_chroma_grey_yuv,
 (void *)   vlc_entry__video_filter_grain,
 (void *)   vlc_entry__video_filter_gradient,
 (void *)   vlc_entry__video_filter_gradfun,
 (void *)   vlc_entry__misc_gnutls,
 (void *)   vlc_entry__video_output_opengl_gles2,
 (void *)   vlc_entry__video_output_opengl_glconv_android,
 (void *)   vlc_entry__control_gestures,
 (void *)   vlc_entry__video_filter_gaussianblur,
 (void *)   vlc_entry__audio_filter_gain,
 (void *)   vlc_entry__codec_g711,
 (void *)   vlc_entry__access_ftp,
 (void *)   vlc_entry__video_filter_freeze,
 (void *)   vlc_entry__text_renderer_freetype_freetype,
 (void *)   vlc_entry__video_filter_fps,
 (void *)   vlc_entry__meta_engine_folder,
 (void *)   vlc_entry__audio_mixer_float_mixer,
 (void *)   vlc_entry__video_output_flaschen,
 (void *)   vlc_entry__demux_flacsys,
 (void *)   vlc_entry__codec_flac,
 (void *)   vlc_entry__misc_fingerprinter,
 (void *)   vlc_entry__access_filesystem,
 (void *)   vlc_entry__logger_file,
 (void *)   vlc_entry__keystore_file,
 (void *)   vlc_entry__video_output_fb,
 (void *)   vlc_entry__video_filter_extract,
 (void *)   vlc_entry__misc_playlist_export,
 (void *)   vlc_entry__demux_mpeg_es,
 (void *)   vlc_entry__video_filter_erase,
 (void *)   vlc_entry__audio_filter_equalizer,
 (void *)   vlc_entry__video_output_opengl_egl_android,
 (void *)   vlc_entry__codec_edummy,
 (void *)   vlc_entry__video_filter_edgedetection,
 (void *)   vlc_entry__spu_dynamicoverlay_dynamicoverlay,
 (void *)   vlc_entry__access_dvdread,
 (void *)   vlc_entry__access_dvdnav,
 (void *)   vlc_entry__codec_dvbsub,
 (void *)   vlc_entry__access_dvb_dvb,
 (void *)   vlc_entry__control_dummy,
 (void *)   vlc_entry__access_dtv_dtv,
 (void *)   vlc_entry__access_dsm_dsm,
 (void *)   vlc_entry__audio_filter_channel_mixer_dolby,
 (void *)   vlc_entry__demux_directory,
 (void *)   vlc_entry__demux_demux_stl,
 (void *)   vlc_entry__demux_demuxdump,
 (void *)   vlc_entry__stream_out_chromecast_demux_chromecast,
 (void *)   vlc_entry__demux_demux_cdg,
 (void *)   vlc_entry__video_filter_deinterlace_deinterlace,
 (void *)   vlc_entry__stream_filter_decomp,
 (void *)   vlc_entry__codec_ddummy,
 (void *)   vlc_entry__codec_dav1d,
 (void *)   vlc_entry__codec_cvdsub,
 (void *)   vlc_entry__video_filter_croppadd,
 (void *)   vlc_entry__logger_console,
 (void *)   vlc_entry__audio_filter_compressor,
 (void *)   vlc_entry__video_filter_colorthres,
 (void *)   vlc_entry__video_splitter_clone,
#ifndef ANDROID_ARMV8A
 (void *)   vlc_entry__arm_neon_chroma_yuv_neon,
#endif
 (void *)   vlc_entry__audio_filter_chorus_flanger,
 (void *)   vlc_entry__video_chroma_chain,
 (void *)   vlc_entry__codec_cdg,
 (void *)   vlc_entry__codec_cc,
 (void *)   vlc_entry__video_filter_canvas,
 (void *)   vlc_entry__demux_caf,
 (void *)   vlc_entry__stream_filter_cache_read,
 (void *)   vlc_entry__stream_filter_cache_block,
 (void *)   vlc_entry__video_filter_bluescreen,
 (void *)   vlc_entry__video_filter_blend,
 (void *)   vlc_entry__video_filter_blendbench,
 (void *)   vlc_entry__video_filter_ball,
 (void *)   vlc_entry__demux_avi_avi,
 (void *)   vlc_entry__access_avio,
 (void *)   vlc_entry__demux_avformat_avformat,
 (void *)   vlc_entry__codec_avcodec_avcodec,
 (void *)   vlc_entry__demux_au,
 (void *)   vlc_entry__misc_audioscrobbler,
 (void *)   vlc_entry__audio_filter_converter_audio_format,
 (void *)   vlc_entry__spu_audiobargraph_v,
 (void *)   vlc_entry__audio_filter_audiobargraph_a,
 (void *)   vlc_entry__demux_asf_asf,
 (void *)   vlc_entry__stream_extractor_archive,
 (void *)   vlc_entry__codec_araw,
 (void *)   vlc_entry__codec_aom,
 (void *)   vlc_entry__video_filter_antiflicker,
 (void *)   vlc_entry__video_output_android_android_window,
 (void *)   vlc_entry__logger_android_logger,
 (void *)   vlc_entry__video_output_android_android_display,
 (void *)   vlc_entry__audio_output_android_audiotrack,
 (void *)   vlc_entry__video_filter_anaglyph,
 (void *)   vlc_entry__audio_output_amem,
 (void *)   vlc_entry__video_filter_alphamask,
 (void *)   vlc_entry__demux_aiff,
 (void *)   vlc_entry__audio_output_afile,
 (void *)   vlc_entry__codec_aes3,
 (void *)   vlc_entry__audio_output_adummy,
 (void *)   vlc_entry__codec_adpcm,
 (void *)   vlc_entry__video_filter_adjust,
 (void *)   vlc_entry__stream_filter_adf,
 (void *)   vlc_entry__demux_adaptive_adaptive,
 (void *)   vlc_entry__access_output_udp,
 (void *)   vlc_entry__access_output_access_output_shout,
 (void *)   vlc_entry__access_output_access_output_rist,
 (void *)   vlc_entry__access_output_access_output_livehttp,
 (void *)   vlc_entry__access_output_http,
 (void *)   vlc_entry__access_output_file,
 (void *)   vlc_entry__access_output_dummy,
 (void *)   vlc_entry__access_mms_access_mms,
 (void *)   vlc_entry__access_imem,
 (void *)   vlc_entry__access_concat,
 (void *)   vlc_entry__codec_a52,
 (void *)   NULL
};
